import type { ButtonMode } from '@/lib/insights/button-mode';
import { GenerateButton } from './generate-button';

type Props = {
  mode: 'current' | 'past';
  buttonMode: ButtonMode;
};

export function HeaderBlock({ mode, buttonMode }: Props) {
  return (
    <div className="flex items-start justify-between gap-4">
      <div className="space-y-1.5">
        <p className="text-[10px] font-medium uppercase tracking-[0.08em] text-muted-foreground/70">
          {mode === 'current' ? 'Today' : 'Archived'}
        </p>
        <h1 className="text-xl font-semibold tracking-tight">Insights</h1>
        <p className="max-w-md text-sm text-muted-foreground">
          Weekly check-in on spending, goals, and recurring outflows —
          generated by Claude.
        </p>
      </div>
      <GenerateButton mode={buttonMode} />
    </div>
  );
}
