import { desc, gte } from 'drizzle-orm';
import { type NextRequest, NextResponse } from 'next/server';
import { isAuthorizedCronRequest } from '@/lib/cron/auth';
import { db } from '@/lib/db';
import { type ErrorLog, errorLog, users } from '@/lib/db/schema';
import { env } from '@/lib/env';
import { logError, logRun } from '@/lib/logger';

export const runtime = 'nodejs';
export const maxDuration = 30;

const DAY_MS = 24 * 60 * 60 * 1000;
const MAX_ERRORS_DISPLAYED = 50;
const EXPECTED_BALANCE_RUNS = 4;

/**
 * Daily ops digest. Schedule: 14:00 UTC (6am PT).
 *
 * Reads error_log rows from the last 24h and emails a summary via
 * Resend. Two row types surface differently:
 *   - level='error' → table of failures (truncated past 50)
 *   - level='info'  → "did each cron actually run" health check
 *
 * One email per user with a non-null email; v1 has one user so this
 * is one email per day. Sends BEFORE writing the cron.digest run row,
 * so the digest never includes itself in the next day's count.
 */
export async function GET(request: NextRequest) {
  if (!isAuthorizedCronRequest(request)) {
    return new NextResponse('unauthorized', { status: 401 });
  }

  const startedAt = Date.now();
  const since = new Date(Date.now() - DAY_MS);

  const rows = await db
    .select()
    .from(errorLog)
    .where(gte(errorLog.occurredAt, since))
    .orderBy(desc(errorLog.occurredAt));

  const errors = rows.filter((r) => r.level === 'error');
  const runs = rows.filter((r) => r.level === 'info');

  const userRows = await db.select().from(users);

  let sent = 0;
  let failed = 0;
  for (const user of userRows) {
    if (!user.email) continue;
    try {
      const subject =
        errors.length > 0
          ? `Foothold digest — ${errors.length} error${errors.length === 1 ? '' : 's'}`
          : 'Foothold digest — all clear';
      const html = renderDigest(errors, runs);

      await sendEmail({
        from: env.AUTH_EMAIL_FROM,
        to: user.email,
        subject,
        html,
      });
      sent++;
    } catch (err) {
      failed++;
      await logError('cron.digest.send', err, { email: user.email });
    }
  }

  await logRun(
    'cron.digest',
    `${sent} sent, ${failed} failed (${errors.length} errors, ${runs.length} runs)`,
    {
      duration_ms: Date.now() - startedAt,
      errors: errors.length,
      runs: runs.length,
      sent,
      failed,
    },
  );

  return NextResponse.json({
    sent,
    failed,
    errors: errors.length,
    runs: runs.length,
  });
}

async function sendEmail(args: {
  from: string;
  to: string;
  subject: string;
  html: string;
}): Promise<void> {
  const res = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${env.AUTH_RESEND_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(args),
  });
  if (!res.ok) {
    throw new Error(`Resend ${res.status}: ${await res.text()}`);
  }
}

function renderDigest(errors: ErrorLog[], runs: ErrorLog[]): string {
  const today = new Date().toISOString().slice(0, 10);
  return `<div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:640px;color:#222">
  <h2 style="margin:0 0 16px">Foothold digest — ${today}</h2>
  ${renderErrorsSection(errors)}
  ${renderHealthSection(runs)}
  <p style="font-size:12px;color:#888;margin-top:32px">Generated by /api/cron/digest. Window: last 24h.</p>
</div>`;
}

function renderErrorsSection(errors: ErrorLog[]): string {
  if (errors.length === 0) {
    return `<h3 style="margin:24px 0 8px">Errors</h3><p>None ✓</p>`;
  }
  const display = errors.slice(0, MAX_ERRORS_DISPLAYED);
  const overflow = errors.length - display.length;
  const rows = display
    .map(
      (e) =>
        `<tr><td style="padding:6px 12px;border-top:1px solid #eee;font-family:monospace;white-space:nowrap">${formatTime(e.occurredAt)}</td><td style="padding:6px 12px;border-top:1px solid #eee;font-family:monospace">${escapeHtml(e.op)}</td><td style="padding:6px 12px;border-top:1px solid #eee">${escapeHtml(e.message)}</td></tr>`,
    )
    .join('');
  const footer =
    overflow > 0
      ? `<p style="margin-top:8px;color:#888">…and ${overflow} more (truncated).</p>`
      : '';
  return `<h3 style="margin:24px 0 8px">Errors (${errors.length})</h3>
<table style="border-collapse:collapse;width:100%;font-size:14px">
  <thead><tr style="text-align:left;background:#f6f6f6"><th style="padding:8px 12px">Time UTC</th><th style="padding:8px 12px">Op</th><th style="padding:8px 12px">Message</th></tr></thead>
  <tbody>${rows}</tbody>
</table>${footer}`;
}

function renderHealthSection(runs: ErrorLog[]): string {
  const lines: string[] = [];

  const nightlySync = runs.find((r) => r.op === 'cron.nightly_sync');
  lines.push(
    nightlySync
      ? `<li>Nightly sync: ran at ${formatTime(nightlySync.occurredAt)} UTC — ${escapeHtml(nightlySync.message)} ✓</li>`
      : `<li>Nightly sync: NOT SEEN in last 24h ⚠</li>`,
  );

  const balanceRuns = runs.filter((r) => r.op === 'cron.balance_refresh');
  lines.push(
    balanceRuns.length === EXPECTED_BALANCE_RUNS
      ? `<li>Balance refresh: ran ${balanceRuns.length}/${EXPECTED_BALANCE_RUNS} times ✓</li>`
      : `<li>Balance refresh: ran ${balanceRuns.length}/${EXPECTED_BALANCE_RUNS} times ⚠</li>`,
  );

  const insight = runs.find((r) => r.op === 'cron.insight');
  if (insight) {
    lines.push(
      `<li>Weekly insight: ran at ${formatTime(insight.occurredAt)} UTC — ${escapeHtml(insight.message)} ✓</li>`,
    );
  }

  return `<h3 style="margin:24px 0 8px">Cron health</h3>
<ul style="margin:0;padding-left:20px;line-height:1.8">${lines.join('')}</ul>`;
}

function formatTime(d: Date): string {
  return d.toISOString().slice(11, 19);
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
