import { auth } from '@/auth';
import { GenerateButton } from '@/components/insights/generate-button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { getLatestInsight } from '@/lib/db/queries/insights';

const DAY_MS = 24 * 60 * 60 * 1000;

function yesterdayKey(): string {
  return new Date(Date.now() - DAY_MS).toISOString().slice(0, 10);
}

function formatGeneratedAt(d: Date): string {
  const diffMs = Date.now() - d.getTime();
  const diffMin = Math.floor(diffMs / (60 * 1000));
  if (diffMin < 1) return 'just now';
  if (diffMin < 60) return `${diffMin} min ago`;
  const diffHr = Math.floor(diffMin / 60);
  if (diffHr < 24) return `${diffHr}h ago`;
  return d.toISOString().slice(0, 10);
}

export default async function InsightsPage() {
  const session = await auth();
  if (!session?.user) return null;

  const latest = await getLatestInsight(session.user.id);
  const currentWeekKey = yesterdayKey();
  const isCurrentWeek = latest?.weekStart && latest.weekEnd === currentWeekKey;

  return (
    <div className="px-8 py-8 max-w-3xl mx-auto space-y-6">
      <div className="flex items-start justify-between gap-4">
        <div className="space-y-1">
          <h1 className="text-3xl font-semibold tracking-tight">Insights</h1>
          <p className="text-sm text-muted-foreground">
            Weekly check-in on spending, goals, and recurring outflows —
            generated by Claude.
          </p>
        </div>
        <GenerateButton hasExisting={!!latest} />
      </div>

      {latest ? (
        <Card>
          <CardHeader>
            <CardTitle className="text-base font-medium">
              Week of {latest.weekStart} – {latest.weekEnd}
            </CardTitle>
            <CardDescription>
              Generated {formatGeneratedAt(latest.generatedAt)}
              {!isCurrentWeek && (
                <span className="ml-1 text-amber-600">
                  · click Regenerate for the current week
                </span>
              )}
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4 text-sm leading-relaxed whitespace-pre-wrap">
              {latest.narrative}
            </div>
          </CardContent>
        </Card>
      ) : (
        <Card>
          <CardHeader>
            <CardTitle>No insights yet</CardTitle>
            <CardDescription>
              Click &ldquo;Generate insights&rdquo; to have Claude summarize
              the last 7 days. Each generation costs ~$0.001 and takes a
              few seconds.
            </CardDescription>
          </CardHeader>
        </Card>
      )}
    </div>
  );
}
