import { Sparkles } from 'lucide-react';
import { auth } from '@/auth';
import { GenerateButton } from '@/components/insights/generate-button';
import { getLatestInsight } from '@/lib/db/queries/insights';

const DAY_MS = 24 * 60 * 60 * 1000;

function yesterdayKey(): string {
  return new Date(Date.now() - DAY_MS).toISOString().slice(0, 10);
}

function formatGeneratedAt(d: Date): string {
  const diffMs = Date.now() - d.getTime();
  const diffMin = Math.floor(diffMs / (60 * 1000));
  if (diffMin < 1) return 'just now';
  if (diffMin < 60) return `${diffMin} min ago`;
  const diffHr = Math.floor(diffMin / 60);
  if (diffHr < 24) return `${diffHr}h ago`;
  return d.toLocaleDateString(undefined, {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
}

function formatWeekRange(start: string, end: string): string {
  const s = new Date(start);
  const e = new Date(end);
  return `${s.toLocaleDateString(undefined, { month: 'short', day: 'numeric' })} – ${e.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}`;
}

export default async function InsightsPage() {
  const session = await auth();
  if (!session?.user) return null;

  const latest = await getLatestInsight(session.user.id);
  const currentWeekKey = yesterdayKey();
  const isCurrentWeek = latest?.weekStart && latest.weekEnd === currentWeekKey;

  return (
    <div className="mx-auto max-w-3xl space-y-8 px-4 py-6 sm:px-8 sm:py-10">
      <div className="flex items-start justify-between gap-4">
        <div className="space-y-1.5">
          <p className="text-[10px] font-medium uppercase tracking-[0.08em] text-muted-foreground/70">
            Today
          </p>
          <h1 className="text-xl font-semibold tracking-tight">Insights</h1>
          <p className="max-w-md text-sm text-muted-foreground">
            Weekly check-in on spending, goals, and recurring outflows —
            generated by Claude.
          </p>
        </div>
        <GenerateButton hasExisting={!!latest} />
      </div>

      {latest ? (
        <article className="space-y-5 rounded-card border border-border bg-surface-elevated p-6 sm:p-8">
          <header className="flex items-baseline justify-between gap-3 border-b border-border pb-4">
            <div className="space-y-1">
              <p className="text-[10px] font-medium uppercase tracking-[0.08em] text-muted-foreground/70">
                Week of
              </p>
              <p className="font-mono text-sm tabular-nums text-foreground">
                {formatWeekRange(latest.weekStart, latest.weekEnd)}
              </p>
            </div>
            <p className="text-xs text-muted-foreground">
              Generated {formatGeneratedAt(latest.generatedAt)}
              {!isCurrentWeek && (
                <span className="ml-1 text-amber-600 dark:text-amber-400">
                  · regenerate for current week
                </span>
              )}
            </p>
          </header>
          <div className="font-serif text-[17px] leading-[1.7] text-foreground/95 whitespace-pre-wrap">
            {latest.narrative}
          </div>
        </article>
      ) : (
        <EmptyState />
      )}
    </div>
  );
}

function EmptyState() {
  return (
    <div className="rounded-card border border-border bg-surface-elevated p-8 text-center sm:p-12">
      <span className="mx-auto grid h-14 w-14 place-items-center rounded-pill bg-gradient-hero text-white">
        <Sparkles className="h-6 w-6" />
      </span>
      <h2 className="mt-5 text-lg font-semibold tracking-tight">
        No insights yet
      </h2>
      <p className="mx-auto mt-2 max-w-md text-sm text-muted-foreground">
        Click "Generate insights" to have Claude summarize the last 7 days
        of spending, goal progress, and recurring outflows. Each
        generation costs a fraction of a cent and takes a few seconds.
      </p>
    </div>
  );
}
